"""high_score

Revision ID: 389b80a75c63
Revises: ca9a354adb71
Create Date: 2023-04-19 22:20:54.125892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389b80a75c63'
down_revision = 'ca9a354adb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('high_score')

    # ### end Alembic commands ###
